//Se agarran 10 pokemones por atributo

const Pokedex = [
   //water-type pokemons
    {
name: "Piplup",
type: "Water",
atk: 51,
def: 10,
hp: 53, 
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/piplup.avif",
    },
     {
name: "Prinplup",
type: "water",
atk: 66,
def: 68,
hp: 64,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/prinplup.avif",
    },

        {
name: "Empoleon",
type: "water",
atk: 86,
def: 88,
hp: 84,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/empoleon.avif",
    },
        {
name: "Magikarp",
type: "water",
atk: 10,
def: 55,
hp: 20,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/magikarp.avif",
    },
        {
name: "Gyarados",
type: "water",
atk: 125,
def: 79,
hp: 95,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/gyarados.avif",
    },
        {
name: "Psyduck",
type: "water",
atk: 52,
def: 48,
hp: 50,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/psyduck.avif",
    },
        {
name: "Golduck",
type: "water",
atk: 82,
def: 78,
hp:80,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/golduck.avif",
    },
        {
name: "Buizel",
type: "water",
atk: 65,
def: 35,
hp:55,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/buizel.avif",
    },
        {
name: "Floatzel",
type: "water",
atk: 105,
def: 55,
hp:85,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/floatzel.avif",
    },
        {
name: "Shellos",
type: "water",
atk: 48,
def: 48,
hp:76,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/shellos.avif",
    },
            {
name: "Gastrodon",
type: "water",
atk: 83,
def: 68,
hp:111,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/gastrodon.avif",
    },
            {
name: "Goldeen",
type: "water",
atk: 67,
def: 60,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/goldeen.avif",
    },
            {
name: "Seaking",
type: "water",
atk: 92,
def: 65,
hp:80,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/seaking.avif",
    },
            {
name: "Barboach",
type: "water",
atk: 48,
def: 43,
hp:50,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/barboach.avif",
    },
            {
name: "Whiscash",
type: "water",
atk: 78,
def: 73,
hp: 110,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/whiscash.avif",
    },
            {
name: "Wooper",
type: "water",
atk: 45,
def: 45,
hp:55,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/wooper.avif",
    },
            {
name: "Quagsire",
type: "water",
atk: 85,
def: 85,
hp:95,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/quagsire.avif",
    },
            {
name: "Wingull",
type: "water",
atk: 30,
def: 30,
hp:40,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/wingull.avif",
    },
            {
name: "Pelipper",
type: "water",
atk: 50,
def: 100,
hp:60,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/pelipper.avif",
    },
            {
name: "Marill",
type: "water",
atk: 20,
def: 50,
hp:70,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/marill.avif",
    },
            {
name: "Azumarill",
type: "water",
atk: 50,
def: 80,
hp:100,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/azumarill.avif",
    },
            {
name: "Remoraid",
type: "water",
atk: 65,
def: 35,
hp:35,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/remoraid.avif",
    },
            {
name: "Octillery",
type: "water",
atk: 105,
def: 75,
hp:75,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/octillery.avif",
    },
    {
name: "Finneon",
type: "water",
atk: 49,
def: 56,
hp:49,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/finneon.avif",
    },
    {
name: "Lumineon",
type: "water",
atk: 69,
def: 76,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/lumineon.avif",
    },
    {
name: "Tentacool",
type: "water/poison",
atk: 40,
def: 35,
hp:40,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/tentacool.avif",
    },
    {
name: "Tentacruel",
type: "water/poison",
atk: 70,
def: 65,
hp:80,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/tentacruel.avif",
    },
     {
name: "Feebas",
type: "water",
atk: 15,
def: 20,
hp:20,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/feebas.avif",
    },
     {
name: "Milotic",
type: "water",
atk: 60,
def: 79,
hp:95,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/milotic.avif",
    },
     {
name: "Mantyke",
type: "water",
atk: 20,
def: 50,
hp:45,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/mantyke.avif",
    },
     {
name: "Mantine",
type: "water",
atk: 40,
def: 70,
hp:85,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/mantine.avif",
    },
     {
name: "Palkia",
type: "water/dragon",
atk: 120,
def: 100,
hp:90,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/palkia.avif",
    },
     {
name: "Manaphy",
type: "water",
atk: 100,
def: 100,
hp:100,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/manaphy.avif",
    },

    //grass-type pokemons
     {
name: "Turtwig",
type: "grass",
atk: 68,
def: 64,
hp:55,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/turtwig.avif",
    },
     {
name: "Grotle",
type: "grass",
atk: 89,
def: 85,
hp:75,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/grotle.avif",
    },
    {
name: "Torterra",
type: "grass",
atk: 109,
def: 105,
hp:95,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/torterra.avif",
    },
    {
name: "Budew",
type: "grass/poison",
atk: 30,
def: 35,
hp:40,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/budew.avif",
    },
    {
name: "Roselia",
type: "grass/poison",
atk: 60,
def: 45,
hp:50,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/roselia.avif",
    },
    {
name: "Roserade",
type: "grass/poison",
atk: 70,
def: 65,
hp:60,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/roserade.avif",
    },
    {
name: "Wormadam",
type: "grass",
atk: 59,
def: 85,
hp:60,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/wormadam-plant.avif",
    },
    {
name: "Cherubi",
type: "grass",
atk: 35,
def: 45,
hp:45,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/cherubi.avif",
    },
    {
name: "Cherrim",
type: "grass",
atk: 60,
def: 70,
hp:70,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/cherrim.avif",
    },
    {
name: "Carnivine",
type: "grass",
atk: 100,
def: 72,
hp:74,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/carnivine.avif",
    },
    {
name: "Snover",
type: "grass/ice",
atk: 62,
def: 50,
hp:60,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/snover.avif",
    },
       {
name: "Abomasnow",
type: "grass/ice",
atk: 92,
def: 75,
hp:90,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/abomasnow.avif",
    },

    //fire-type pokemons
           {
name: "Chimchar",
type: "fire",
atk: 58,
def: 44,
hp:44,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/chimchar.avif",
    },
              {
name: "Monferno",
type: "fire/fighting",
atk: 78,
def: 52,
hp:64,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/monferno.avif",
    },
              {
name: "Infernape",
type: "fire/fighting",
atk: 104,
def: 71,
hp:76,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/infernape.avif",
    },
              {
name: "Ponyta",
type: "fire",
atk: 85,
def: 55,
hp:50,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/ponyta.avif",
    },
              {
name: "Rapidash",
type: "fire",
atk: 100,
def: 70,
hp:65,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/rapidash.avif",
    },

    //normal-type pokemons
              {
name: "Starly",
type: "normal",
atk: 55,
def: 30,
hp:40,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/starly.avif",
    },
                {
name: "Staravia",
type: "normal",
atk: 75,
def: 50,
hp:55,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/staravia.avif",
    },
                {
name: "Staraptor",
type: "normal",
atk: 120,
def: 70,
hp:85,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/staraptor.avif",
    },
                {
name: "Bidoof",
type: "normal",
atk: 45,
def: 40,
hp:59,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/bidoof.avif",
    },

                {
name: "Bibarel",
type: "normal",
atk: 85,
def: 60,
hp:79,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/bibarel.avif",
    },
                {
name: "Aipom",
type: "normal",
atk: 70,
def: 55,
hp:55,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/aipom.avif",
    },
                {
name: "Ambipom",
type: "normal",
atk: 100,
def: 66,
hp:75,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/ambipom.avif",
    },

                {
name: "Buneary",
type: "normal",
atk: 66,
def: 44,
hp:55,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/buneary.avif",
    },
                {
name: "Lopunny",
type: "normal",
atk: 76,
def: 84,
hp:65,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/lopunny.avif",
    },
                {
name: "Glameow",
type: "normal",
atk: 55,
def: 42,
hp:49,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/glameow.avif",
    },
                {
name: "Purugly",
type: "normal",
atk: 82,
def: 64,
hp:71,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/purugly.avif",
    },
                {
name: "Happiny",
type: "normal",
atk: 5,
def: 5,
hp:100,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/happiny.avif",
    },
                {
name: "Chansey",
type: "normal",
atk: 5,
def: 5,
hp:250,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/chansey.avif",
    },
                {
name: "Blissey",
type: "normal",
atk: 10,
def: 10,
hp:255,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/blissey.avif",
    },
                {
name: "Chatot",
type: "normal/flying",
atk: 65,
def: 45,
hp:76,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/chatot.avif",
    },
                {
name: "Hoothoot",
type: "normal",
atk: 30,
def: 30,
hp:60,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/hoothoot.avif",
    },
                    {
name: "Noctowl",
type: "normal",
atk: 50,
def: 50,
hp:100,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/noctowl.avif",
    },

                    {
name: "Munchlax",
type: "normal",
atk: 85,
def: 40,
hp:135,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/munchlax.avif",
    },

                    {
name: "Snorlax",
type: "normal",
atk: 110,
def: 65,
hp:160,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/snorlax.avif",
    },

                    {
name: "Girafarig",
type: "normal/psychic",
atk: 80,
def: 65,
hp:70,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/girafarig.avif",
    },

                    {
name: "Farigiraf",
type: "normal/psychic",
atk: 90,
def: 70,
hp:120,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/farigiraf.avif",
    },
                        {
name: "Azurill",
type: "normal/fairy",
atk: 20,
def: 40,
hp:50,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/azurill.avif",
    },

    //bug-type pokemons
    
                            {
name: "Kricketot",
type: "bug",
atk: 25,
def: 41,
hp:37,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/kricketot.avif",
    },
                            {
name: "Kricketune",
type: "bug",
atk: 85,
def: 51,
hp:77,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/kricketune.avif",
    },
                            {
name: "Burmy",
type: "bug",
atk: 29,
def: 45,
hp:40,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/burmy-plant.avif",
    },
                            {
name: "Wormadam",
type: "bug",
atk: 59,
def: 85,
hp:60,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/wormadam-plant.avif",
    },
                            {
name: "Mothim",
type: "bug",
atk: 94,
def: 50,
hp:70,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/mothim.avif",
    },
                            {
name: "Wurmple",
type: "bug",
atk: 45,
def: 35,
hp:45,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/wurmple.avif",
    },
                            {
name: "Silcoon",
type: "bug",
atk: 35,
def: 55,
hp:50,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/silcoon.avif",
    },
                            {
name: "Cascoon",
type: "bug",
atk: 35,
def: 55,
hp:50,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/cascoon.avif",
    },
                            {
name: "Beautifly",
type: "bug/flying",
atk: 70,
def: 50,
hp:60,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/beautifly.avif",
    },
                            {
name: "Dustox",
type: "bug/poison",
atk: 50,
def: 70,
hp:60,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/dustox.avif",
    },
                            {
name: "Combee",
type: "bug/flying",
atk: 30,
def: 42,
hp:30,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/combee.avif",
    },
                            {
name: "Vespiquen",
type: "bug/flying",
atk: 80,
def: 102,
hp:70,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/vespiquen.avif",
    },
                            {
name: "Heracross",
type: "bug",
atk: 125,
def: 75,
hp:80,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/heracross.avif",
    },

    //electric-type pokemons
                            {
name: "Shinx",
type: "electric",
atk: 65,
def: 34,
hp:45,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/shinx.avif",
    },
                            {
name: "Luxio",
type: "electric",
atk: 85,
def: 49,
hp:60,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/luxio.avif",
    },
                                {
name: "Luxray",
type: "electric",
atk: 120,
def: 79,
hp:80,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/luxray.avif",
    },
                                {
name: "Pachirisu",
type: "electric",
atk: 45,
def: 70,
hp:60,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/pachirisu.avif",
    },
                                {
name: "Pichu",
type: "electric",
atk: 40,
def: 15,
hp:20,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/pichu.avif",
    },
                                {
name: "Pikachu",
type: "electric",
atk: 55,
def: 40,
hp:35,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/pikachu.avif",
    },
                                {
name: "Raichu",
type: "electric",
atk: 90,
def: 55,
hp:60,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/raichu.avif",
    },

    //psychic=type pokemons
                                    {
name: "Abra",
type: "psychic",
atk: 20,
def: 15,
hp:25,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/abra.avif",
    },
                                        {
name: "Kadabra",
type: "psychic",
atk: 35,
def: 30,
hp:40,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/kadabra.avif",
    },
                                        {
name: "Alakazam",
type: "psychic",
atk: 50,
def: 45,
hp:55,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/alakazam.avif",
    },
                                        {
name: "Chingling",
type: "psychic",
atk: 30,
def: 50,
hp:45,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/chingling.avif",
    },
                                        {
name: "Chimecho",
type: "psychic",
atk: 50,
def: 80,
hp:75,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/chimecho.avif",
    },
                                        {
name: "Mime Jr.",
type: "psychic",
atk: 25,
def: 45,
hp:20,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/mime-jr.avif",
    },
                                        {
name: "Mr. Mime",
type: "psychic",
atk: 45,
def: 65,
hp:40,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/mr-mime.avif",
    },
                                        {
name: "Unown",
type: "psychic",
atk: 72,
def: 48,
hp:48,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/unown.avif",
    },
                                        {
name: "Uxie",
type: "psychic",
atk: 75,
def: 130,
hp:75,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/uxie.avif",

//poison=type pokemons
    },
                                        {
name: "Zubat",
type: "poison-flying",
atk: 45,
def: 35,
hp:40,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/zubat.avif",
    },
                                        {
name: "Golbat",
type: "poison-flying",
atk: 80,
def: 70,
hp:75,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/golbat.avif",
    },
                                        {
name: "Crobat",
type: "poison/flying",
atk: 90,
def: 80,
hp:85,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/crobat.avif",
    },
                                        {
name: "Stunky",
type: "poison/dark",
atk: 63,
def: 47,
hp:63,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/stunky.avif",
    },

                                            {
name: "Skuntank",
type: "poison/dark",
atk: 93,
def: 67,
hp:103,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/skuntank.avif",
    },
                                            {
name: "Skorupi",
type: "poison/bug",
atk: 50,
def: 90,
hp:40,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/skorupi.avif",
    },
                                            {
name: "Drapion",
type: "poison/dark",
atk: 90,
def: 110,
hp:70,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/drapion.avif",
    },
                                                {
name: "Croagunk",
type: "poison/fighting",
atk: 61,
def: 40,
hp:48,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/croagunk.avif",
    },
                                                    {
name: "Toxicroak",
type: "poison/fighting",
atk: 106,
def: 65,
hp:83,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/toxicroak.avif",
    },
    

    //rock-type pokemons
    {
name: "Geodude",
type: "rock/ground",
atk: 80,
def: 100,
hp:40,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/geodude.avif",
    },
     {
name: "Graveler",
type: "rock/ground",
atk: 95,
def: 115,
hp:55,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/graveler.avif",
    },

     {
name: "Golem",
type: "rock/ground",
atk: 120,
def: 130,
hp:80,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/golem.avif",
    },

     {
name: "Onix",
type: "rock/ground",
atk: 45,
def: 160,
hp:35,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/onix.avif",
    },

     {
name: "Cranidos",
type: "rock",
atk: 125,
def: 40,
hp:67,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/cranidos.avif",
    },

     {
name: "Rampardos",
type: "rock",
atk: 165,
def: 60,
hp:97,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/rampardos.avif",
    },

     {
name: "Shieldon",
type: "rock/steel",
atk: 42,
def: 118,
hp:30,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/shieldon.avif",
    },

     {
name: "Bastiodon",
type: "rock/steel",
atk: 52,
def: 168,
hp:60,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/bastiodon.avif",
    },

     {
name: "Bonsly",
type: "rock",
atk: 80,
def: 95,
hp:50,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/bonsly.avif",
    },
     {
name: "Sudowoodo",
type: "rock",
atk: 100,
def: 115,
hp:70,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/sudowoodo.avif",
    },

    //ghost=type pokemons
     {
name: "Drifloon",
type: "ghost",
atk: 50,
def: 34,
hp:90,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/drifloon.avif",
    },
     {
name: "Drifblim",
type: "ghost/fying",
atk: 80,
def: 44,
hp:150,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/drifblim.avif",
    },
     {
name: "Gastly",
type: "ghost/poison",
atk: 35,
def: 30,
hp:30,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/gastly.avif",
    },
    {
name: "Haunter",
type: "ghost/poison",
atk: 50,
def: 45,
hp:45,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/haunter.avif",
    },

    {
name: "Gengar",
type: "ghost/poison",
atk: 65,
def: 60,
hp:60,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/gengar.avif",
    },

    {
name: "Misdreavus",
type: "ghost",
atk: 60,
def: 60,
hp:60,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/misdreavus.avif",
    },


    {
name: "Mismagius",
type: "ghost",
atk: 60,
def: 60,
hp:60,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/mismagius.avif",
    },

    {
name: "Spiritomb",
type: "ghost/dark",
atk: 92,
def: 108,
hp:50,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/spiritomb.avif",
    },

    //fighting-type pokemons
     {
name: "Meditite",
type: "fighting/psychic",
atk: 40,
def: 55,
hp:30,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/meditite.avif",
    },
    {
name: "Medicham",
type: "fighting/psychic",
atk: 60,
def: 75,
hp:60,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/medicham.avif",
    },
    {
name: "Riolu",
type: "fighting",
atk: 70,
def: 40,
hp:40,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/riolu.avif",
    },
    {
name: "Lucario",
type: "fighting/steel",
atk: 110,
def: 70,
hp:70,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/lucario.avif",
    },

    //dragon-type pokemons
  {
name: "Gible",
type: "dragon/ground",
atk: 70,
def: 45,
hp:58,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/gible.avif",
    },
      {
name: "Gabite",
type: "dragon/ground",
atk: 90,
def: 65,
hp:68,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/gabite.avif",
    },
      {
name: "Garchomp",
type: "dragon/ground",
atk: 130,
def: 95,
hp:108,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/garchomp.avif",
    },

    //steel-type pokemons
      {
name: "Steelix",
type: "steel/ground",
atk: 85,
def: 200,
hp:75,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/steelix.avif",
    },
     {
name: "Bronzor",
type: "steel/psychic",
atk: 24,
def: 86,
hp:57,
evolves: true,
img: "https://img.pokemondb.net/artwork/avif/bronzor.avif",
    },

         {
name: "Bronzong",
type: "steel/psychic",
atk: 89,
def: 116,
hp:67,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/bronzong.avif",
    },
           {
name: "Dialga",
type: "steel/dragon",
atk: 120,
def: 120,
hp:100,
evolves: false,
img: "https://img.pokemondb.net/artwork/avif/dialga.avif",
    },





    
]